### ISSUE TITLE
any way to vary command line options for cluster startup?

### ISSUE THREAD

**Issue by minektur** [TomOgoma/cockroach-installer#2]
I note that this doesn't have a --join option so that this would be a primary node or a 'startup' node in a cluster.

Presumably I could edit the service file to include a --join command line option....

What do you do in production? I mean, I'd love to have automated startup (and restart) via systemd, but in one case I'd like to have no join and in another I'd like to have join, depending on the status of the cluster.  I dont see how I can make this work.  I'd be better off just writing a shell script that works outside of systemd...

**Comment by tomogoma** [comment]
Ideally we have each node in a different virtual machine. So the primary node uses the script as is, but then we modify the service unit files for nodes that need to join the cluster (adding the --join arg) - so some manual modification for you on every extra node in the cluster there - which, truly, can become a headache.

Currently I'm working on another project so may not have time to action this immediately but I'm willing to, eventually, make changes to the installer script to allow modification of these options when running it (maybe pass on the args which will be appended to the exec line).

I haven't really thought about the best approach for this so any ideas are welcome ...or in case you are willing to get your hands dirty in the meantime, I'll be very okay with merging a pull request.

**Comment by tomogoma** [comment]
Hi @minektur , I just added functionality that I think solves this issue, see the updated README for details. I'll close this for now.
